# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Engineer
email: lucia_reyes@brown.edu
description: Software Engineer Website.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo: 

# Social settings
github_username: lucyreyes
twitter_username: lucyreyes_
facebook_URL: lucyreyes
instagram_username: lucyreyes_
dribbble_username: andrewbanchich
500px_username: andrewbanchich
phone: 857-869-3781

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
